project:
  type: website
  output-dir: docs

website:
  title: "Renata Beco"
  navbar:
    background: darkgreen
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Outreach"
        href: outreach.qmd
      - text: "Contact & CV"
        href: contact.qmd
      
       

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
  

