---
title: "Publications"
---

You can check my publications below or on my [Google Scholar](https://scholar.google.com/citations?user=P-4Mq5oAAAAJ&hl=en&oi=ao). Please email me (rpereir4\@vols.utk.edu) requesting a pdf copy if you can't have access.

1.       Valtuille T., Ubaid F.K., **Beco R.**, Brandão R.A. (2024) Diet of the vulnerable White-browed Guan Penelope jacucaca (Galliformes, Cracidae) in two contrasting Caatinga fragments in Northeastern Brazil. Ethology Ecology & Evolution, 36(3), 245–261. <https://doi.org/10.1080/03949370.2023.2263410>

2.       Glaser, T., Martins, P., **Beco, R.**, Bento, C. A., Cappellari, A. R., La Banca Oliveira, S., ... & Ulrich, H. (2024). Impairment of adenosine signaling disrupts early embryo development: unveiling the underlying mechanisms. *Frontiers in Pharmacology*, *14*, 1328398. <https://doi.org/10.3389/fphar.2023.1328398>

3.       Santos, C. S. L., C. Licarião, W. Girão, **R. Beco**, and F. K. Ubaid. (2022). First description of the nest and eggs of Ceará Leaftosser *Sclerurus cearensis*, with a review of the breeding biology of genus *Sclerurus*. *Bulletin of the British Ornithologists’ Club*, *142*(2), 155-163. <https://doi.org/10.25226/bboc.v142i2.2022.a2>

4.       Ubaid, F. K., and **R. Beco**. (2022). Interspecific foraging association between the cryptic forest-falcon, *Micrastur mintoni* and primates in an Amazon rainforest in Brazil. *Acta Amazonica*, *52*, 49-52. <https://doi.org/10.1590/1809-4392202101362>

5.       **Beco R.**,L. F. Silveira, E. P. Derryberry and G. A. Bravo. (2021). Ecology and behavior predict an evolutionary trade-off between song complexity and elaborate plumages in antwrens (Aves, Thamnophilidae). Evolution. <https://doi.org/10.1111/evo.14325>

6.       Fecchio, A., M. R. Lima, J. A. Bell, F. Schunck, A. H. Corrêa, **R. Beco**, A. E. Jahn, C. S. Fontana, T. W. da Silva, M. Repenning, É. M. Braga, J. E. Garcia, C. Lugarini, J. C. R. Silva, L. H. M. Andrade, J. H. Dispoto, C. C. dos Anjos, J. D. Weckstein, K. Kirchgatter, V. A. Ellis, R. E. Ricklefs, and G. M. De La Torre. (2021). Loss of forest cover and host functional diversity increases prevalence of avian malaria parasites in the Atlantic Forest. International Journal for Parasitology. <https://doi.org/10.1016/j.ijpara.2021.01.001>

7.       Bravo, G. A., B. M. Whitney, R. Belmonte-lopes, M. R. Bornschein, N. Aristizábal, **R. Beco**, J. Battilana, L. N. Naka, A. Aleixo, M. R. Pie, L. F. Silveira, E. P. Derryberry, and R. T. Brumfield. (2021). Phylogenomic analyses reveal non-monophyly of the antbird genera *Herpsilochmus* and *Sakesphorus* (Thamnophilidae), with description of a new genus for *Herpsilochmus sellowi*. Ornithology, 138, 1-16. <https://doi.org/10.1093/ornithology/ukab025>

8.       Glaser, T., S. L. B. De Oliveira, A. Cheffer, **R. Beco**, P. Martins, M. Fornazari, C. Lameu, H. M. Costa Junior, R. Coutinho-Silva, and H. Ulrich (2014). Modulation of mouse embryonic stem cell proliferation and neural differentiation by the P2X7 receptor. PLoS ONE 9:96281. <https://doi.org/10.1371/journal.pone.0096281>
